# Generated by Django 5.1.1 on 2024-11-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeList',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=16)),
                ('cook_type', models.CharField(max_length=2)),
                ('cook_level', models.CharField(max_length=2)),
                ('cook_time', models.CharField(max_length=5)),
                ('food_description', models.CharField(max_length=100)),
                ('food_image', models.CharField(max_length=100)),
                ('food_ingredient_image', models.CharField(max_length=100)),
                ('food_recipe_image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'recipe_list',
                'managed': False,
            },
        ),
    ]
